KEYWORDS = [
    "looking for artist",
    "need to comm",
    "looking to commission",
    "looking to comm",
    "need artist",
    "artist to commission",
    "artist to comm",
    "want to commission",
    "wanna commission",
    "wanna comm",
    "need to commission",
    "need art",
    "anyone know any artist",
    "any artist",
    "going to commission",
    "gotta commission",
    "gotta comm",
    "going to comm",
    "hiring artist",
    "someome to commission",
    "someone to comm",
    "need 3D model",
    "want 3D model",
    "neet to get art",
    "wanting to commission",
    "need to hire artist",
    "any artist out there",
    "need to find artist",
    "willing to commission",
    "willing to comm",
    "willing to get art",
    "can someone draw",
    "anyone has commissions open",
    "anyone open for commissions",
    "anyone open for comms",
    "need model",
    "need vtuber",
    "need thumbnail",
    "need emotes",
    "artist call",
    "who to commission",
    "who to comm",
    "anyone has comms open",
    "anybody open for commissions",
    "anybody open for comms",
    "anybody has commissions open",
    "anybody has comms open",
    "finding artist",
    "tryna find artist",
    "trying to find artist",
    "if you're an artist",
    "if you're a artist",
    "if you are an artist",
    "if you are artist",
    "artist hunt",
    "hunting artist",
    "need drawn",
    "want drawn",
    "who does art",
    "who does commissions",
    "who does comms",
    "pixel artist",
    "looking for animator",
    "need animator",
    "any animator",
    "need art done",
    "need animation done",
    "3D model",
    "do you know any artist",
    "commissioning artist",
    "be commissioning",
    "who got commissions open",
    "who got comms open",
    "who is open for commissions",
    "who is open for comms",
    "might commission",
    "might comm",
    "might be commissioning",
    "seeking artist",
    "seeking animator",
    "need rigger",
    "need rigging",
    "any rigger",
    "need rigging done",
    "name your artists",
    "who draws",
    "vrc avatar",
    "vrchat avatar",
    "pngtuber",
    "need chibi",
    "need banner",
    "need logo",
    "reference sheet",
    "background artist"
]
